package com.example.kotlinjc_tests.models

data class DataObject(
    var id: String,
    var name: String
)

val mockData = mutableListOf<DataObject>(
    DataObject(id = "1", name = "Name One"),
    DataObject(id = "2", name = "Name Two"),
    DataObject(id = "3", name = "Name Three"),
    DataObject(id = "4", name = "Name Four"),
    DataObject(id = "5", name = "Name Five"),
    DataObject(id = "6", name = "Name Six"),
    DataObject(id = "7", name = "Name Seven"),
    DataObject(id = "8", name = "Name Eight"),
    DataObject(id = "9", name = "Name Nine"),
    DataObject(id = "10", name = "Name Ten"),
    DataObject(id = "11", name = "Name Eleven"),
    DataObject(id = "12", name = "Name Twelve"),
    DataObject(id = "13", name = "Name Thirteen"),
    DataObject(id = "14", name = "Name Fourteen"),
    DataObject(id = "15", name = "Name Fifteen"),
    DataObject(id = "16", name = "Name Sixteen"),
    DataObject(id = "17", name = "Name Seventeen"),
    DataObject(id = "18", name = "Name Eighteen"),
    DataObject(id = "19", name = "Name Nineteen"),
    DataObject(id = "20", name = "Name Twenty"),
    DataObject(id = "21", name = "Name Twenty One"),
    DataObject(id = "22", name = "Name Twenty Two"),
    DataObject(id = "23", name = "Name Twenty Three"),
    DataObject(id = "24", name = "Name Twenty Four"),
    DataObject(id = "25", name = "Name Twenty Five"),
    DataObject(id = "26", name = "Name Twenty Six"),
    DataObject(id = "27", name = "Name Twenty Seven"),
    DataObject(id = "28", name = "Name Twenty Eight"),
    DataObject(id = "29", name = "Name Twenty Nine"),
    DataObject(id = "30", name = "Name Thirty"),
    DataObject(id = "31", name = "Name Thirty One"),
    DataObject(id = "32", name = "Name Thirty Two"),
    DataObject(id = "33", name = "Name Thirty Three"),
    DataObject(id = "34", name = "Name Thirty Four"),
    DataObject(id = "35", name = "Name Thirty Five"),
    DataObject(id = "36", name = "Name Thirty Six"),
    DataObject(id = "37", name = "Name Thirty Seven"),
    DataObject(id = "38", name = "Name Thirty Eight"),
    DataObject(id = "39", name = "Name Thirty Nine"),
    DataObject(id = "40", name = "Name Forty"),
    DataObject(id = "41", name = "Name Forty One"),
    DataObject(id = "42", name = "Name Forty Two"),
    DataObject(id = "43", name = "Name Forty Three"),
    DataObject(id = "44", name = "Name Forty Four"),
    DataObject(id = "45", name = "Name Forty Five"),
    DataObject(id = "46", name = "Name Forty Six"),
    DataObject(id = "47", name = "Name Forty Seven"),
    DataObject(id = "48", name = "Name Forty Eight"),
    DataObject(id = "49", name = "Name Forty Nine"),
    DataObject(id = "50", name = "Name Fifty"),
    DataObject(id = "51", name = "Name Fifty One"),
    DataObject(id = "52", name = "Name Fifty Two"),
    DataObject(id = "53", name = "Name Fifty Three"),
    DataObject(id = "54", name = "Name Fifty Four"),
    DataObject(id = "55", name = "Name Fifty Five"),
    DataObject(id = "56", name = "Name Fifty Six"),
    DataObject(id = "57", name = "Name Fifty Seven"),
    DataObject(id = "58", name = "Name Fifty Eight"),
    DataObject(id = "59", name = "Name Fifty Nine"),
    DataObject(id = "60", name = "Name Sixty"),
    DataObject(id = "61", name = "Name Sixty One"),
    DataObject(id = "62", name = "Name Sixty Two"),
    DataObject(id = "63", name = "Name Sixty Three"),
    DataObject(id = "64", name = "Name Sixty Four"),
    DataObject(id = "65", name = "Name Sixty Five"),
    DataObject(id = "66", name = "Name Sixty Six"),
    DataObject(id = "67", name = "Name Sixty Seven"),
    DataObject(id = "68", name = "Name Sixty Eight"),
    DataObject(id = "69", name = "Name Sixty Nine"),
    DataObject(id = "70", name = "Name Seventy"),
    DataObject(id = "71", name = "Name Seventy One"),
    DataObject(id = "72", name = "Name Seventy Two"),
    DataObject(id = "73", name = "Name Seventy Three"),
    DataObject(id = "74", name = "Name Seventy Four"),
    DataObject(id = "75", name = "Name Seventy Five"),
    DataObject(id = "76", name = "Name Seventy Six"),
    DataObject(id = "77", name = "Name Seventy Seven"),
    DataObject(id = "78", name = "Name Seventy Eight"),
    DataObject(id = "79", name = "Name Seventy Nine"),
    DataObject(id = "80", name = "Name Eighty"),
    DataObject(id = "81", name = "Name Eighty One"),
    DataObject(id = "82", name = "Name Eighty Two"),
    DataObject(id = "83", name = "Name Eighty Three"),
    DataObject(id = "84", name = "Name Eighty Four"),
    DataObject(id = "85", name = "Name Eighty Five"),
    DataObject(id = "86", name = "Name Eighty Six"),
    DataObject(id = "87", name = "Name Eighty Seven"),
    DataObject(id = "88", name = "Name Eighty Eight"),
    DataObject(id = "89", name = "Name Eighty Nine"),
    DataObject(id = "90", name = "Name Ninety"),
    DataObject(id = "91", name = "Name Ninety One"),
    DataObject(id = "92", name = "Name Ninety Two"),
    DataObject(id = "93", name = "Name Ninety Three"),
    DataObject(id = "94", name = "Name Ninety Four"),
    DataObject(id = "95", name = "Name Ninety Five"),
    DataObject(id = "96", name = "Name Ninety Six"),
    DataObject(id = "97", name = "Name Ninety Seven"),
    DataObject(id = "98", name = "Name Ninety Eight"),
    DataObject(id = "99", name = "Name Ninety Nine"),
    DataObject(id = "100", name = "Name One Hundred")
)
